name: Testing

on:
  push:
    branches:
      - "*"
  pull_request:
    branchess:
      - "*"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.13
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install conda-libmamba-solver
        run: |
          conda install -n base conda-libmamba-solver
      - name: Install dependencies
        run: |
          sudo conda env update --file environment.yml --name base --experimental-solver=libmamba  
      - name: Test with pytest
        run: |
          pip install -U pytest
          pytest
