name: Testing

on:
  push:
    branches:
      - "*"
  pull_request:
    branchess:
      - "*"


jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: environment.yml
          python-version: 3.8.11
          auto-activate-base: false
      - name: Test with pytest
        run: |
          conda install pytest
          pytest
